from oop10 import Tienda
from oop11 import Producto

gucci = Tienda('Gucci')
jabon = Producto(1,'jabon',100,'Uso_Personal')
afeitadora = Producto(2,'afeitadora',60,'Uso_Personal')
shampoo = Producto(3,'shampoo',30,'Uso_Personal')
cepillo = Producto(4,'cepillo',50,'Uso_Personal')
franela = Producto(5,'franela',50,'Ropa')
gorra = Producto(6,'gorra',50,'Ropa')
jean = Producto(7,'jean',50,'Ropa')
gucci.agregar_producto(jabon)
gucci.agregar_producto(afeitadora)
gucci.agregar_producto(shampoo)
gucci.agregar_producto(cepillo)
gucci.agregar_producto(franela)
gucci.agregar_producto(gorra)
gucci.agregar_producto(jean)
gucci.ver_productos()
gucci.inflacion(10)
gucci.ver_productos()
print('')
gucci.hacer_liquidacion(50,'Ropa')
gucci.ver_productos()
print('')
gucci.vender_producto(1)
gucci.vender_producto(4)
print('')
gucci.ver_productos()
